import jsPDF from "jspdf";

interface PDFData {
  businessName: string;
  manualTask: string;
  tools: string;
  automationPlan: string;
}

export function generatePDF(data: PDFData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Dark navy header background
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageWidth, 50, "F");

  // AutoConsult logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("AutoConsult", margin, 22);

  // Tagline
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(156, 163, 175);
  doc.text("AI Business Automation Consultant", margin, 31);

  // Date on the right
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text(date, pageWidth - margin, 22, { align: "right" });

  // Report title
  doc.setFontSize(9);
  doc.text("Automation Report", pageWidth - margin, 31, { align: "right" });

  let y = 65;

  // Prepared for section
  doc.setFillColor(243, 244, 246);
  doc.roundedRect(margin, y - 8, contentWidth, 22, 3, 3, "F");
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("PREPARED FOR", margin + 8, y);
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text(data.businessName, margin + 8, y + 9);

  y += 30;

  // The Challenge section
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("The Challenge", margin, y);

  // Underline
  doc.setDrawColor(17, 24, 39);
  doc.setLineWidth(0.5);
  doc.line(margin, y + 2, margin + 35, y + 2);

  y += 10;
  doc.setTextColor(75, 85, 99);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const challengeLines = doc.splitTextToSize(data.manualTask, contentWidth);
  doc.text(challengeLines, margin, y);
  y += challengeLines.length * 6 + 10;

  // Tools section
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Tools Referenced", margin, y);
  doc.setDrawColor(17, 24, 39);
  doc.line(margin, y + 2, margin + 42, y + 2);

  y += 10;
  const toolsList = data.tools.split(",").map((t) => t.trim()).filter(Boolean);
  toolsList.forEach((tool) => {
    doc.setFillColor(229, 231, 235);
    doc.roundedRect(margin, y - 4, doc.getTextWidth(tool) + 10, 8, 2, 2, "F");
    doc.setTextColor(55, 65, 81);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(tool, margin + 5, y + 1);
    margin === 20 && (y += 12);
  });

  y += 8;

  // Automation Plan section
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Your Automation Plan", margin, y);
  doc.setDrawColor(17, 24, 39);
  doc.line(margin, y + 2, margin + 55, y + 2);

  y += 12;

  // Parse and render plan steps
  const steps = data.automationPlan
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);

  steps.forEach((step, i) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    // Step number circle
    doc.setFillColor(17, 24, 39);
    doc.circle(margin + 3, y - 1, 3, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.text(String(i + 1), margin + 3, y + 0.5, { align: "center" });

    // Step text
    doc.setTextColor(55, 65, 81);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const stepLines = doc.splitTextToSize(step, contentWidth - 12);
    doc.text(stepLines, margin + 10, y);
    y += stepLines.length * 6 + 6;
  });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFillColor(17, 24, 39);
  doc.rect(0, footerY - 5, pageWidth, 20, "F");
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by AutoConsult — automation-app-umber.vercel.app", pageWidth / 2, footerY + 3, { align: "center" });

  // Save
  const filename = `${data.businessName.replace(/\s+/g, "-").toLowerCase()}-automation-plan.pdf`;
  doc.save(filename);
}